### ISSUE TITLE
Issue running w/ 10.7.0 Linux x86_64

### ISSUE THREAD

**Issue by chiefy** [crobibero/Jellyfin.Channels.LazyMan#11]
More of a Linux guy and new to JF so any help would be great!

```
[2021-03-09 15:05:05.342 -05:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Channels.LazyMan.LazyManChannel"
System.TypeLoadException: Could not load type 'MediaBrowser.Common.Net.IHttpClient' from assembly 'MediaBrowser.Common, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.get_Signature()
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.RuntimeConstructorInfo.GetParameters()
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type) in /home/chief/.cache/yay/jellyfin/src/jellyfin-10.7.0/Emby.Server.Implementations/ApplicationHost.cs:line 400
```

**Comment by chiefy** [comment]
sorry, wasn't sure if it was the same issues as #10 thanks @crobibero
