### ISSUE TITLE
All NHL Games show "Not Available Yet"

### ISSUE THREAD

**Issue by uberlinuxguy** [crobibero/Jellyfin.Channels.LazyMan#43]
I'm not sure what I could be doing wrong, but I get the game listings for all the days, however when I try to play something, past or present, it says they are all "Not available yet" and I get this in the log:
```
[21:37:43] [INF] [32] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[21:37:55] [INF] [38] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[21:40:28] [WRN] [19] Jellyfin.Channels.LazyMan.GameApi.PowerSportsApi: [LazyMan][GetStreamUrlAsync] Response contains Not!
[21:40:42] [ERR] [19] Emby.Server.Implementations.Library.MediaSourceManager: Error getting media sources
System.Collections.Generic.KeyNotFoundException: The given key 'null' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Jellyfin.Channels.LazyMan.LazyManChannel.GetChannelItemMediaInfo(String id, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Channels.ChannelManager.GetChannelItemMediaSourcesInternal(IRequiresMediaInfoCallback channel, String id, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Channels.ChannelManager.GetDynamicMediaSources(BaseItem item, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.MediaSourceManager.GetDynamicMediaSources(BaseItem item, IMediaSourceProvider provider, CancellationToken cancellationToken)
```

What could I possibly be missing?

**Comment by crobibero** [comment]
The service is no longer available, so this plugin will no longer function.
