### ISSUE TITLE
Error while running in nightly

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [crobibero/Jellyfin.Channels.LazyMan#5]
```
[03:02:09] [ERR] [4] App: Error in Channel Image Provider
System.ArgumentException: No image info for chapter images
   at MediaBrowser.Controller.Entities.BaseItem.GetImages(ImageType imageType)
   at MediaBrowser.Providers.Manager.ImageSaver.SaveImage(BaseItem item, Stream source, String mimeType, ImageType type, Nullable`1 imageIndex, Nullable`1 saveLocallyWithMedia, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ItemImageProvider.RefreshFromProvider(BaseItem item, IDynamicImageProvider provider, ImageRefreshOptions refreshOptions, TypeOptions savedOptions, LibraryOptions libraryOptions, ICollection`1 downloadedImages, RefreshResult result, CancellationToken cancellationToken)
```

**Comment by crobibero** [comment]
Does playback work?

**Comment by ThatNerdyPikachu** [comment]
Nothing appears in the channel.

**Comment by crobibero** [comment]
Thanks for bringing it to my attention. The plugin doesn't seem to be doing anything when it's opened so I think there's an issue on the server side, or I have to do something new with the channel

**Comment by crobibero** [comment]
Jellyfin v10.5.0 was just release, I'm able to play games from last night still. Can you check with the stable version?

**Comment by xkronusx** [comment]
Having the same issue on Jellyfin V10.5.0 latest docker image.

Nothing comes up in the folder when opened.
